################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/src/ccsbcs.c \
../Middlewares/src/diskio.c \
../Middlewares/src/ff.c \
../Middlewares/src/ff_gen_drv.c \
../Middlewares/src/sd_diskio.c \
../Middlewares/src/sdram_diskio.c \
../Middlewares/src/unicode.c 

OBJS += \
./Middlewares/src/ccsbcs.o \
./Middlewares/src/diskio.o \
./Middlewares/src/ff.o \
./Middlewares/src/ff_gen_drv.o \
./Middlewares/src/sd_diskio.o \
./Middlewares/src/sdram_diskio.o \
./Middlewares/src/unicode.o 

C_DEPS += \
./Middlewares/src/ccsbcs.d \
./Middlewares/src/diskio.d \
./Middlewares/src/ff.d \
./Middlewares/src/ff_gen_drv.d \
./Middlewares/src/sd_diskio.d \
./Middlewares/src/sdram_diskio.d \
./Middlewares/src/unicode.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/src/ccsbcs.o: ../Middlewares/src/ccsbcs.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/ccsbcs.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/diskio.o: ../Middlewares/src/diskio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/diskio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/ff.o: ../Middlewares/src/ff.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/ff.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/ff_gen_drv.o: ../Middlewares/src/ff_gen_drv.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/ff_gen_drv.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/sd_diskio.o: ../Middlewares/src/sd_diskio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/sd_diskio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/sdram_diskio.o: ../Middlewares/src/sdram_diskio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/sdram_diskio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/src/unicode.o: ../Middlewares/src/unicode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/src/unicode.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

