################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ADIF.c \
../Src/Codec_Gains.c \
../Src/DS3231.c \
../Src/Display.c \
../Src/FIR_Coefficients.c \
../Src/Process_DSP.c \
../Src/SDR_Audio.c \
../Src/SiLabs.c \
../Src/Sine_table.c \
../Src/button.c \
../Src/decode_ft8.c \
../Src/gen_ft8.c \
../Src/log_file.c \
../Src/main.c \
../Src/options.c \
../Src/stm32f7xx_it.c \
../Src/traffic_manager.c 

OBJS += \
./Src/ADIF.o \
./Src/Codec_Gains.o \
./Src/DS3231.o \
./Src/Display.o \
./Src/FIR_Coefficients.o \
./Src/Process_DSP.o \
./Src/SDR_Audio.o \
./Src/SiLabs.o \
./Src/Sine_table.o \
./Src/button.o \
./Src/decode_ft8.o \
./Src/gen_ft8.o \
./Src/log_file.o \
./Src/main.o \
./Src/options.o \
./Src/stm32f7xx_it.o \
./Src/traffic_manager.o 

C_DEPS += \
./Src/ADIF.d \
./Src/Codec_Gains.d \
./Src/DS3231.d \
./Src/Display.d \
./Src/FIR_Coefficients.d \
./Src/Process_DSP.d \
./Src/SDR_Audio.d \
./Src/SiLabs.d \
./Src/Sine_table.d \
./Src/button.d \
./Src/decode_ft8.d \
./Src/gen_ft8.d \
./Src/log_file.d \
./Src/main.d \
./Src/options.d \
./Src/stm32f7xx_it.d \
./Src/traffic_manager.d 


# Each subdirectory must supply rules for building sources it contributes
Src/ADIF.o: ../Src/ADIF.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/ADIF.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/Codec_Gains.o: ../Src/Codec_Gains.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/Codec_Gains.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/DS3231.o: ../Src/DS3231.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/DS3231.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/Display.o: ../Src/Display.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/Display.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/FIR_Coefficients.o: ../Src/FIR_Coefficients.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/FIR_Coefficients.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/Process_DSP.o: ../Src/Process_DSP.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/Process_DSP.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/SDR_Audio.o: ../Src/SDR_Audio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/SDR_Audio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/SiLabs.o: ../Src/SiLabs.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/SiLabs.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/Sine_table.o: ../Src/Sine_table.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/Sine_table.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/button.o: ../Src/button.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/button.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/decode_ft8.o: ../Src/decode_ft8.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/decode_ft8.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/gen_ft8.o: ../Src/gen_ft8.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/gen_ft8.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/log_file.o: ../Src/log_file.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/log_file.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/main.o: ../Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/options.o: ../Src/options.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/options.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/stm32f7xx_it.o: ../Src/stm32f7xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/stm32f7xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/traffic_manager.o: ../Src/traffic_manager.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Src/traffic_manager.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

