################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../FT8_library/constants.c \
../FT8_library/decode.c \
../FT8_library/encode.c \
../FT8_library/ldpc.c \
../FT8_library/pack.c \
../FT8_library/text.c \
../FT8_library/unpack.c 

OBJS += \
./FT8_library/constants.o \
./FT8_library/decode.o \
./FT8_library/encode.o \
./FT8_library/ldpc.o \
./FT8_library/pack.o \
./FT8_library/text.o \
./FT8_library/unpack.o 

C_DEPS += \
./FT8_library/constants.d \
./FT8_library/decode.d \
./FT8_library/encode.d \
./FT8_library/ldpc.d \
./FT8_library/pack.d \
./FT8_library/text.d \
./FT8_library/unpack.d 


# Each subdirectory must supply rules for building sources it contributes
FT8_library/constants.o: ../FT8_library/constants.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/constants.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/decode.o: ../FT8_library/decode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/decode.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/encode.o: ../FT8_library/encode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/encode.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/ldpc.o: ../FT8_library/ldpc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/ldpc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/pack.o: ../FT8_library/pack.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/pack.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/text.o: ../FT8_library/text.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/text.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
FT8_library/unpack.o: ../FT8_library/unpack.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Inc -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/STM32746G_DISCOVERY" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/wm8994" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/ft5336" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Utilities/Fonts" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Drivers/BSP/rk043fn48h" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/FT8_library" -I"C:/STM32F746_32k_ADX_QSO_RTC_Bands_ADIF_DX_Un0_EditRTC_2/Katy/Middlewares/src" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"FT8_library/unpack.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

